# Generated by Django 6.0.8 on 2026-08-30 08:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dialogue', '0013_alter_dialogue_source'),
        ('identity', '0011_account_tip_wallet_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invite_token', models.CharField(max_length=64, unique=True)),
                ('pseudonym', models.CharField(max_length=80)),
                ('approach', models.CharField(blank=True, default='', max_length=300)),
                ('languages', models.CharField(default='ru', max_length=60)),
                ('rate_sol', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('solana_address', models.CharField(blank=True, default='', max_length=60)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.OneToOneField(blank=True, help_text='Bound when the therapist claims the invite token.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Therapist profile',
                'verbose_name_plural': 'Therapist profiles',
                'ordering': ('pseudonym',),
            },
        ),
        migrations.CreateModel(
            name='TherapySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('payment_claimed', 'Client says payment sent'), ('paid', 'Paid (therapist confirmed)'), ('declined', 'Declined by therapist'), ('done', 'Done')], db_index=True, default='awaiting_payment', max_length=32)),
                ('note', models.CharField(blank=True, default='', max_length=280)),
                ('price_sol', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapy_sessions', to=settings.AUTH_USER_MODEL)),
                ('client_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapy_sessions', to='identity.anonymoussession')),
                ('dialogue', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapy_session', to='dialogue.dialogue')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='therapy.therapistprofile')),
            ],
            options={
                'verbose_name': 'Therapy session',
                'verbose_name_plural': 'Therapy sessions',
                'ordering': ('-created_at',),
            },
        ),
    ]
