# Generated by Django 6.0.8 on 2026-08-31 22:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0012_account_tip_wallet_verified_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('done', 'Done')], default='new', max_length=16)),
                ('text', models.TextField()),
                ('page', models.CharField(blank=True, default='', max_length=200)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('reporter_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
                ('reporter_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to='identity.anonymoussession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
