# Generated by Django 6.0.7 on 2026-08-04 17:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_account_helper_org_account_is_helper'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('dialogue_request', 'Dialogue request'), ('support_cloud', 'Support cloud'), ('cloud_approved', 'Support cloud approved'), ('dialogue_opened', 'Dialogue opened'), ('outreach_intro', 'Author outreach intro'), ('message', 'New chat message')], db_index=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='identity.anonymoussession')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient_account', '-created_at'], name='notificatio_recipie_d10241_idx'), models.Index(fields=['recipient_session', '-created_at'], name='notificatio_recipie_da52ab_idx'), models.Index(fields=['recipient_account', 'is_read', '-created_at'], name='notificatio_recipie_a2447b_idx'), models.Index(fields=['recipient_session', 'is_read', '-created_at'], name='notificatio_recipie_30c4fa_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('recipient_account__isnull', False), ('recipient_session__isnull', True)), models.Q(('recipient_account__isnull', True), ('recipient_session__isnull', False)), _connector='OR'), name='notification_exactly_one_recipient')],
            },
        ),
    ]
