# Generated by Django 6.0.7 on 2026-08-05 10:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_account_email_verified_and_more'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDigest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('subject', models.CharField(default='', max_length=200)),
                ('body_text', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True, default='')),
                ('recipient_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_digests', to=settings.AUTH_USER_MODEL)),
                ('recipient_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_digests', to='identity.anonymoussession')),
            ],
            options={
                'verbose_name': 'Email digest',
                'verbose_name_plural': 'Email digests',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['recipient_account', '-created_at'], name='notificatio_recipie_19fdeb_idx'), models.Index(fields=['recipient_session', '-created_at'], name='notificatio_recipie_25ed50_idx'), models.Index(fields=['status', '-created_at'], name='notificatio_status_9b4e62_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('recipient_account__isnull', False), ('recipient_session__isnull', True)), models.Q(('recipient_account__isnull', True), ('recipient_session__isnull', False)), _connector='OR'), name='email_digest_exactly_one_recipient')],
            },
        ),
    ]
