# Generated by Django 6.0.8 on 2026-08-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('dialogue_request', 'Dialogue request'), ('support_cloud', 'Support cloud'), ('cloud_approved', 'Support cloud approved'), ('dialogue_opened', 'Dialogue opened'), ('outreach_intro', 'Author outreach intro'), ('message', 'New chat message'), ('dialogue_deleted', 'Dialogue deleted'), ('silent_empathy', 'Silent empathy / rays'), ('help_requested', 'Help request'), ('help_accepted', 'Help request accepted'), ('dialogue_request_review', 'Dialogue request helper review'), ('report_resolved', 'Report resolved')], db_index=True, max_length=32),
        ),
    ]
