# Generated by Django 6.0.7 on 2026-07-31 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('abuse', 'Abuse / harassment'), ('spam', 'Spam'), ('self_harm', 'Self-harm concern'), ('other', 'Other')], max_length=32)),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('resolved_hidden', 'Resolved (content hidden)'), ('resolved_dismissed', 'Resolved (dismissed)')], db_index=True, default='open', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_note', models.TextField(blank=True, default='')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_filed', to=settings.AUTH_USER_MODEL)),
                ('from_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_filed', to='identity.anonymoussession')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stories.story')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', '-created_at'], name='moderation__status_282342_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('from_account__isnull', False), ('status', 'open')), fields=('story', 'from_account'), name='unique_open_report_per_account_story'), models.UniqueConstraint(condition=models.Q(('from_session__isnull', False), ('status', 'open')), fields=('story', 'from_session'), name='unique_open_report_per_session_story')],
            },
        ),
    ]
