# Generated by Django 6.0.7 on 2026-07-31 14:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocked_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to='identity.anonymoussession')),
                ('blocker_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to=settings.AUTH_USER_MODEL)),
                ('blocker_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to='identity.anonymoussession')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('blocker_account__isnull', False), ('blocker_session__isnull', True)), models.Q(('blocker_account__isnull', True), ('blocker_session__isnull', False)), _connector='OR'), name='block_exactly_one_blocker'), models.CheckConstraint(condition=models.Q(models.Q(('blocked_account__isnull', False), ('blocked_session__isnull', True)), models.Q(('blocked_account__isnull', True), ('blocked_session__isnull', False)), _connector='OR'), name='block_exactly_one_blocked'), models.UniqueConstraint(fields=('blocker_account', 'blocker_session', 'blocked_account', 'blocked_session'), name='unique_block_pair')],
            },
        ),
    ]
