# Generated by Django 6.0.7 on 2026-07-31 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0003_alter_dialogue_options_remove_dialogue_invite_token_and_more'),
        ('moderation', '0002_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='message',
            field=models.ForeignKey(blank=True, help_text='Optional: report targets a chat message (story still set for queue).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='dialogue.message'),
        ),
    ]
