# Generated by Django 6.0.8 on 2026-08-28 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0010_help_request'),
        ('identity', '0007_voice_retention'),
        ('moderation', '0003_report_message'),
        ('stories', '0005_story_voice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='unique_open_report_per_account_story',
        ),
        migrations.RemoveConstraint(
            model_name='report',
            name='unique_open_report_per_session_story',
        ),
        migrations.AlterField(
            model_name='report',
            name='message',
            field=models.ForeignKey(blank=True, help_text='Story report may omit this; help-chat report has a message and no story.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='dialogue.message'),
        ),
        migrations.AlterField(
            model_name='report',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stories.story'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(('story__isnull', False), ('message__isnull', False), _connector='OR'), name='report_story_or_message'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('from_account__isnull', False), ('status', 'open'), ('story__isnull', False)), fields=('story', 'from_account'), name='unique_open_report_per_account_story'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('from_session__isnull', False), ('status', 'open'), ('story__isnull', False)), fields=('story', 'from_session'), name='unique_open_report_per_session_story'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('from_account__isnull', False), ('message__isnull', False), ('status', 'open'), ('story__isnull', True)), fields=('message', 'from_account'), name='unique_open_help_report_account_message'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('from_session__isnull', False), ('message__isnull', False), ('status', 'open'), ('story__isnull', True)), fields=('message', 'from_session'), name='unique_open_help_report_session_message'),
        ),
    ]
