# Generated by Django 6.0.8 on 2026-08-31 03:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0013_alter_dialogue_source'),
        ('moderation', '0004_report_nullable_story'),
        ('stories', '0005_story_voice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('reviewing', 'Marked reviewing'), ('hidden', 'Content hidden'), ('removed', 'Content removed'), ('dismissed', 'Report dismissed')], max_length=32)),
                ('reason', models.CharField(blank=True, choices=[('abuse', 'Abuse / harassment'), ('spam', 'Spam'), ('self_harm', 'Self-harm concern'), ('other', 'Other')], default='', help_text='Обязателен для терминальных решений (hide/remove/dismiss).', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_made', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='dialogue.message')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='moderation.report')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='stories.story')),
            ],
            options={
                'verbose_name': 'Moderation action',
                'verbose_name_plural': 'Moderation actions',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['action', '-created_at'], name='moderation__action_9c4f47_idx')],
            },
        ),
    ]
