# Generated by Django 6.0.8 on 2026-09-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0005_moderationaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationaction',
            name='reason',
            field=models.CharField(blank=True, choices=[('abuse', 'Abuse / harassment'), ('spam', 'Spam'), ('self_harm', 'Self-harm concern'), ('other', 'Other')], default='', help_text='Required for terminal decisions (hide/remove/dismiss).', max_length=32),
        ),
    ]
