# Generated by Django 6.0.7 on 2026-07-31 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpathyPulse',
            fields=[
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pulse', serialize=False, to='stories.story')),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empathy Pulse',
                'verbose_name_plural': 'Empathy Pulses',
            },
        ),
        migrations.CreateModel(
            name='SilentEmpathy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empathies_given', to=settings.AUTH_USER_MODEL)),
                ('from_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empathies_given', to='identity.anonymoussession')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empathies', to='stories.story')),
            ],
            options={
                'verbose_name': 'Silent Empathy',
                'verbose_name_plural': 'Silent Empathies',
                'constraints': [models.UniqueConstraint(condition=models.Q(('from_account__isnull', False)), fields=('story', 'from_account'), name='unique_empathy_per_account_story'), models.UniqueConstraint(condition=models.Q(('from_session__isnull', False)), fields=('story', 'from_session'), name='unique_empathy_per_session_story')],
            },
        ),
    ]
