# Generated by Django 6.0.7 on 2026-07-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empathy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='silentempathy',
            name='outreach_opt_in',
            field=models.BooleanField(default=True),
        ),
    ]
