# Generated by Django 6.0.7 on 2026-07-31 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('hidden', 'Hidden'), ('removed', 'Removed')], db_index=True, default='published', max_length=16)),
                ('pseudonym_snapshot', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to=settings.AUTH_USER_MODEL)),
                ('author_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='identity.anonymoussession')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ('-published_at', '-created_at'),
                'indexes': [models.Index(fields=['status', '-published_at'], name='stories_sto_status_386c74_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('author_account__isnull', False), ('author_session__isnull', True)), models.Q(('author_account__isnull', True), ('author_session__isnull', False)), _connector='OR'), name='story_exactly_one_author')],
            },
        ),
    ]
