# Generated by Django 6.0.7 on 2026-07-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='topic',
            field=models.CharField(choices=[('loneliness', 'Одиночество'), ('anxiety', 'Тревога'), ('grief', 'Горе / утрата'), ('exhaustion', 'Выгорание'), ('relationships', 'Отношения'), ('self', 'Отношение к себе'), ('crisis', 'Кризисный момент'), ('other', 'Другое')], db_index=True, default='other', max_length=32),
        ),
    ]
