# Generated by Django 6.0.8 on 2026-08-25 21:20

import apps.stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_story_clouds_last_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='audio',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=apps.stories.models.story_voice_upload_to),
        ),
        migrations.AddField(
            model_name='story',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
