# Generated by Django 6.0.8 on 2026-09-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_story_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='topic',
            field=models.CharField(choices=[('loneliness', 'Loneliness'), ('anxiety', 'Anxiety'), ('grief', 'Grief / loss'), ('exhaustion', 'Burnout'), ('relationships', 'Relationships'), ('self', 'Relationship with self'), ('crisis', 'Crisis moment'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
    ]
