# Generated by Django 6.0.8 on 2026-08-30 06:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutySegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('close_reason', models.CharField(blank=True, choices=[('manual', 'Duty toggled off'), ('stale', 'Heartbeat gap')], default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_segments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Duty segment',
                'verbose_name_plural': 'Duty segments',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['helper', '-started_at'], name='fund_dutyse_helper__7fbb1e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('helper',), name='fund_one_open_segment_per_helper')],
            },
        ),
    ]
