# Generated by Django 6.0.7 on 2026-07-31 15:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('stories', '0002_story_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuietPhrase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('text_ru', models.CharField(max_length=280)),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quiet Phrase',
                'verbose_name_plural': 'Quiet Phrases',
                'ordering': ('sort_order', 'key'),
            },
        ),
        migrations.CreateModel(
            name='SupportCloud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('quiet_phrase', 'Quiet Phrase'), ('free_text', 'Free text (moderated)')], db_index=True, default='quiet_phrase', max_length=32)),
                ('body_snapshot', models.CharField(max_length=500)),
                ('pseudonym_snapshot', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('pending', 'Pending moderation'), ('rejected', 'Rejected')], db_index=True, default='delivered', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_clouds_sent', to=settings.AUTH_USER_MODEL)),
                ('from_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_clouds_sent', to='identity.anonymoussession')),
                ('phrase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clouds', to='support.quietphrase')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_clouds', to='stories.story')),
            ],
            options={
                'verbose_name': 'Support Cloud',
                'verbose_name_plural': 'Support Clouds',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['story', 'status', '-created_at'], name='support_sup_story_i_4e2a2e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('from_account__isnull', False), ('from_session__isnull', True)), models.Q(('from_account__isnull', True), ('from_session__isnull', False)), _connector='OR'), name='support_cloud_exactly_one_sender'), models.UniqueConstraint(condition=models.Q(('from_account__isnull', False), ('kind', 'quiet_phrase'), ('phrase__isnull', False)), fields=('story', 'from_account', 'phrase'), name='unique_quiet_phrase_per_account_story'), models.UniqueConstraint(condition=models.Q(('from_session__isnull', False), ('kind', 'quiet_phrase'), ('phrase__isnull', False)), fields=('story', 'from_session', 'phrase'), name='unique_quiet_phrase_per_session_story')],
            },
        ),
    ]
