# Generated by Django 6.0.7 on 2026-07-31 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportcloud',
            name='helper_badge',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
        migrations.AddField(
            model_name='supportcloud',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportcloud',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportcloud',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clouds_moderated', to=settings.AUTH_USER_MODEL),
        ),
    ]
