# Generated by Django 6.0.7 on 2026-07-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportcloud_helper_badge_supportcloud_is_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quietphrase',
            name='text_en',
            field=models.CharField(blank=True, default='', max_length=280),
        ),
    ]
