# Generated by Django 6.0.8 on 2026-08-31 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_cloud_thread_unique'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportcloud',
            new_name='support_sup_thread__c93351_idx',
            old_name='support_sup_thread__idx',
        ),
    ]
