# Generated by Django 6.0.7 on 2026-07-31 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dialogue', '0001_initial'),
        ('identity', '0001_initial'),
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='author_account',
            field=models.ForeignKey(blank=True, help_text='Author Account when the author is registered.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogues_started', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='author_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogues_started', to='identity.anonymoussession'),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='invitee_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogues_invited', to='identity.anonymoussession'),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='stories.story'),
        ),
    ]
