# Generated by Django 6.0.7 on 2026-07-31 14:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0002_initial'),
        ('identity', '0001_initial'),
        ('stories', '0002_story_topic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialogue',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Dialogue', 'verbose_name_plural': 'Dialogues'},
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='invite_token',
        ),
        migrations.RemoveField(
            model_name='dialogue',
            name='invitee_session',
        ),
        migrations.AddField(
            model_name='dialogue',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='intent',
            field=models.CharField(choices=[('listen', 'Просто выговориться / выслушать'), ('share', 'Поделиться похожим опытом'), ('advice_ok', 'Советы допустимы'), ('mutual', 'Обмен историями')], default='listen', max_length=32),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='peer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogues_as_peer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='peer_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogues_as_peer', to='identity.anonymoussession'),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='author_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogues_as_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='author_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogues_as_author', to='identity.anonymoussession'),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=16),
        ),
        migrations.CreateModel(
            name='DialogueRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intent', models.CharField(choices=[('listen', 'Просто выговориться / выслушать'), ('share', 'Поделиться похожим опытом'), ('advice_ok', 'Советы допустимы'), ('mutual', 'Обмен историями')], max_length=32)),
                ('note', models.CharField(blank=True, default='', max_length=280)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('from_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_requests_sent', to='identity.anonymoussession')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogue_requests', to='stories.story')),
            ],
            options={
                'verbose_name': 'Dialogue request',
                'verbose_name_plural': 'Dialogue requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='dialogue',
            name='request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogue', to='dialogue.dialoguerequest'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dialogue.dialogue')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
                ('from_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_sent', to='identity.anonymoussession')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='dialoguerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('from_account__isnull', False), ('status', 'pending')), fields=('story', 'from_account'), name='unique_pending_request_account'),
        ),
        migrations.AddConstraint(
            model_name='dialoguerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('from_session__isnull', False), ('status', 'pending')), fields=('story', 'from_session'), name='unique_pending_request_session'),
        ),
    ]
