# Generated by Django 6.0.7 on 2026-07-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0003_alter_dialogue_options_remove_dialogue_invite_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='source',
            field=models.CharField(choices=[('request', 'Dialogue request accepted'), ('author_outreach', 'Author outreach to Hearer')], db_index=True, default='request', max_length=32),
        ),
    ]
