# Generated by Django 6.0.7 on 2026-07-31 16:40

import apps.dialogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0004_dialogue_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=apps.dialogue.models.voice_upload_to),
        ),
        migrations.AddField(
            model_name='message',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice note')], db_index=True, default='text', max_length=16),
        ),
        migrations.AddField(
            model_name='message',
            name='source_lang',
            field=models.CharField(blank=True, default='ru', max_length=8),
        ),
        migrations.AddField(
            model_name='message',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
