# Generated by Django 6.0.8 on 2026-08-17 23:17

import apps.dialogue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0005_message_audio_message_duration_ms_message_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ephemeral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=apps.dialogue.models.circle_upload_to),
        ),
        migrations.AlterField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('voice', 'Voice note'), ('circle', 'Circle video')], db_index=True, default='text', max_length=16),
        ),
    ]
