# Generated by Django 6.0.8 on 2026-08-18 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0006_message_circle'),
        ('identity', '0007_voice_retention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='closed_by_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogues_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='closed_by_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogues_closed', to='identity.anonymoussession'),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='hidden_for_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='hidden_for_peer',
            field=models.BooleanField(default=False),
        ),
    ]
