# Generated by Django 6.0.8 on 2026-08-28 22:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0009_chat_list_prefs'),
        ('identity', '0007_voice_retention'),
        ('stories', '0005_story_voice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='source',
            field=models.CharField(choices=[('request', 'Dialogue request accepted'), ('author_outreach', 'Author outreach to Hearer'), ('help', 'Help request accepted')], db_index=True, default='request', max_length=32),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogues', to='stories.story'),
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, default='', max_length=280)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_requests_accepted', to=settings.AUTH_USER_MODEL)),
                ('dialogue', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_request', to='dialogue.dialogue')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='help_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('from_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='help_requests_sent', to='identity.anonymoussession')),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequestSkip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_request_skips', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skips', to='dialogue.helprequest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='helprequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('from_account__isnull', False), ('from_session__isnull', True)), models.Q(('from_account__isnull', True), ('from_session__isnull', False)), _connector='OR'), name='help_request_exactly_one_actor'),
        ),
        migrations.AddConstraint(
            model_name='helprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('from_account__isnull', False), ('status', 'pending')), fields=('from_account',), name='unique_pending_help_account'),
        ),
        migrations.AddConstraint(
            model_name='helprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('from_session__isnull', False), ('status', 'pending')), fields=('from_session',), name='unique_pending_help_session'),
        ),
        migrations.AddConstraint(
            model_name='helprequestskip',
            constraint=models.UniqueConstraint(fields=('request', 'helper'), name='unique_help_skip_helper'),
        ),
    ]
