# Generated by Django 6.0.8 on 2026-08-29 00:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0010_help_request'),
        ('identity', '0007_voice_retention'),
        ('stories', '0005_story_voice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dialoguerequest',
            name='unique_pending_request_account',
        ),
        migrations.RemoveConstraint(
            model_name='dialoguerequest',
            name='unique_pending_request_session',
        ),
        migrations.AlterField(
            model_name='dialoguerequest',
            name='status',
            field=models.CharField(choices=[('awaiting_helper', 'Awaiting helper review'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, default='awaiting_helper', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='dialoguerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('from_account__isnull', False), ('status__in', ['pending', 'awaiting_helper'])), fields=('story', 'from_account'), name='unique_pending_request_account'),
        ),
        migrations.AddConstraint(
            model_name='dialoguerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('from_session__isnull', False), ('status__in', ['pending', 'awaiting_helper'])), fields=('story', 'from_session'), name='unique_pending_request_session'),
        ),
    ]
