# Generated by Django 6.0.8 on 2026-08-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0012_release_awaiting_helper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='source',
            field=models.CharField(choices=[('request', 'Dialogue request accepted'), ('author_outreach', 'Author outreach to Hearer'), ('help', 'Help request accepted'), ('therapy', 'Therapy session (ADR 0022)')], db_index=True, default='request', max_length=32),
        ),
    ]
