# Generated by Django 6.0.8 on 2026-09-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0013_alter_dialogue_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogue',
            name='intent',
            field=models.CharField(choices=[('listen', 'Vent / be heard'), ('share', 'Share a similar experience'), ('advice_ok', 'Advice is welcome'), ('mutual', 'Exchange stories')], default='listen', max_length=32),
        ),
        migrations.AlterField(
            model_name='dialoguerequest',
            name='intent',
            field=models.CharField(choices=[('listen', 'Vent / be heard'), ('share', 'Share a similar experience'), ('advice_ok', 'Advice is welcome'), ('mutual', 'Exchange stories')], max_length=32),
        ),
    ]
