# Generated by Django 6.0.7 on 2026-07-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='helper_org',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='account',
            name='is_helper',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
