# Generated by Django 6.0.7 on 2026-08-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_account_helper_org_account_is_helper'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='notify_digest_frequency',
            field=models.CharField(choices=[('off', 'Off'), ('immediate', 'Immediate'), ('daily', 'Daily digest')], default='daily', max_length=16),
        ),
        migrations.AddField(
            model_name='account',
            name='notify_email_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anonymoussession',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='anonymoussession',
            name='contact_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anonymoussession',
            name='notify_digest_frequency',
            field=models.CharField(choices=[('off', 'Off'), ('immediate', 'Immediate'), ('daily', 'Daily digest')], default='daily', max_length=16),
        ),
        migrations.AddField(
            model_name='anonymoussession',
            name='notify_email_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
