# Generated by Django 6.0.8 on 2026-08-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_account_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='telegram_username',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
