# Generated by Django 6.0.8 on 2026-08-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_account_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='notify_telegram_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
