# Generated by Django 6.0.8 on 2026-08-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_account_notify_telegram_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='telegram_digest_last_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
