# Generated by Django 6.0.8 on 2026-08-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_account_telegram_digest_last_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='voice_retention',
            field=models.CharField(choices=[('delete_on_close', 'Delete on close'), ('keep', 'Keep')], default='delete_on_close', max_length=32),
        ),
        migrations.AddField(
            model_name='anonymoussession',
            name='voice_retention',
            field=models.CharField(choices=[('delete_on_close', 'Delete on close'), ('keep', 'Keep')], default='delete_on_close', max_length=32),
        ),
    ]
