# Generated by Django 6.0.8 on 2026-08-29 00:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_voice_retention'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelperInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('org', models.CharField(blank=True, default='', max_length=120)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helper_invites_created', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helper_invites_accepted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Helper invite',
                'verbose_name_plural': 'Helper invites',
                'ordering': ('-created_at',),
            },
        ),
    ]
