# Generated by Django 6.0.8 on 2026-08-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0008_helper_invite"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_on_duty",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
