# Generated by Django 6.0.8 on 2026-08-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0010_account_helper_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tip_wallet_address',
            field=models.CharField(blank=True, default='', max_length=44),
        ),
    ]
