# Generated by Django 6.0.8 on 2026-08-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_account_tip_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tip_wallet_verified_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]